### ISSUE TITLE
Add support to Vala?

### ISSUE THREAD

**Issue by LeoIannacone** [timonwong/SublimeAStyleFormatter#44]
Hi!

why do not support Vala?

https://wiki.gnome.org/Projects/Vala/Documentation

**Comment by timonwong** [comment]
This plugin is just a **non-official** wrapper for wonderful [astyle](http://astyle.sourceforge.net/) project, if you have any suggestions, you can visit here: http://sourceforge.net/p/astyle/bugs/

But I guess astyle author is unlikely to add Vala support, since astyle has it concentration.
