### ISSUE TITLE
Update Astyle to 2.05

### ISSUE THREAD

**Issue by xu-cheng** [timonwong/SublimeAStyleFormatter#45]
Please update astyle to 2.05 in order to support many C++14 syntax.

**Comment by timonwong** [comment]
Hi, the OSX binaries for both ST2 & ST3 are provided now, linux binaries will come later, but since I don't have windows machines now, it will be later for windows binaries.

**Comment by timonwong** [comment]
Mark as fixed as of 'v3.0.0' release
