### ISSUE TITLE
new version won't work on sublime 2

### ISSUE THREAD

**Issue by DeanKuai** [timonwong/SublimeAStyleFormatter#50]
Hello, my sublime just updated astyle to the newest version and get this error message:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./AStyleFormat.py", line 253, in run
  File "./AStyleFormat.py", line 202, in _get_options
AttributeError: 'module' object has no attribute 'build_astyle_mode_option'

Is that a bug?

**Comment by timonwong** [comment]
It seems the Options.py file in AStyleFormatterLib is neither update to
date, nor loaded into the ST2.
If you upgrade the plugin manually, make sure all files are upgraded.
Finally, a Sublime Text restart may be required.

**Comment by DeanKuai** [comment]
Thank you very much, it works after restarting sublime...
