### ISSUE TITLE
New version still does not work on Sublime Text 2

### ISSUE THREAD

**Issue by Riteme** [timonwong/SublimeAStyleFormatter#51]
I have saw this issue: #50 
But I have restarted Sublime Text 2 many times, it still does not work...
After that, I have reinstalled SublimeAStyleFormatter by Package Manager and it's no use...
Sublime Console output:
```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File "./AStyleFormat.py", line 264, in run
ValueError
```
What's up? What should I do?

**Comment by timonwong** [comment]
Sorry, it's a mistake, I'll release hot fix for that, or, you can edit that file, remove `raise ValueError()` in that line

**Comment by timonwong** [comment]
v3.1.1 released, but it will take a while before package control refresh
