### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by plaidfluff** [timonwong/SublimeAStyleFormatter#52]
Hi, ever since Sublime Text 3 got updated about a week ago, SublimeAStyleFormatter is no longer working for me. If I look at the debug console after it fails to work, I see the following error:

    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
        return self.run(edit)
      File "/Users/jshagam/Library/Application Support/Sublime Text 3/Packages/SublimeAStyleFormatter/AStyleFormat.py", line 270, in run
        except Options.ImproperlyConfigured as e:
    AttributeError: 'module' object has no attribute 'ImproperlyConfigured'

I installed via PackageControl and as far as I know I'm running the latest (uninstalling and reinstalling didn't help).

**Comment by timonwong** [comment]
My guess is that you are not really running the latest version, can you try install this plugin via git?

**Comment by plaidfluff** [comment]
Which contents do you want me to paste? I had already manually inspected the file and saw that the `ImproperlyConfigured` exception is being declared, as far as I can tell, although I'm still pretty much a Python novice.

**Comment by timonwong** [comment]
OK

Have you tried restarting ST? If not, try restart it first, because
submodules won't get updated unless restarting (SublimeAStyleformatter is a
module, and SublimeAStyleFormatter.AStyleFormatLib is a submodule)

**Comment by plaidfluff** [comment]
Restarting Sublime Text fixed it. Sorry for the trouble!
