### ISSUE TITLE
AttributeError: 'module' object has no attribute 'strip_invalid_options_string'？

### ISSUE THREAD

**Issue by Altynai** [timonwong/SublimeAStyleFormatter#55]
Hi, I think it's quite a weird problem to me, some may met before?
When I was formatting a cpp file, the sublime console shows:
![](http://7xij6o.com1.z0.glb.clouddn.com/QQ20150411-1@2x.png)

so I modified the source code with adding a print statement for debug
![](http://7xij6o.com1.z0.glb.clouddn.com/QQ20150411-2@2x.png)

the sublime console shows:
![](http://7xij6o.com1.z0.glb.clouddn.com/QQ20150411-3@2x.png)

the function `strip_invalid_options_string` was not imported, why was it not loaded ?

FYI, I'm using ST3(Dev channel, Build 3082) on OS X(10.10.2)

**Comment by timonwong** [comment]
Have you tried restarting Sublime Text?

**Comment by Altynai** [comment]
oops :scream:
that's working for me, thanks!
