### ISSUE TITLE
Formatter not working buttons not working

### ISSUE THREAD

**Issue by SyedMizbahuddin** [timonwong/SublimeAStyleFormatter#93]
![Screenshot (31)](https://user-images.githubusercontent.com/67075808/124569652-c26d3e80-de63-11eb-8a6f-06eadc3ed2a4.png)
![Screenshot (32)](https://user-images.githubusercontent.com/67075808/124569672-c600c580-de63-11eb-90bc-ef3762ca4c54.png)

Neither for c++ nor for java files the formatter buttons are working both seem to be disabled is there anything that i should be doing  . Not only that it is not showing any commands in command palette as well . I'm trying to solve the issue since a 2 weeks .Any help is appreciated.

**Comment by aditya-25-02** [comment]
yes please same issue ^

**Comment by Haleuan** [comment]
i have same problem , too. It's annoying. : (

**Comment by SyedMizbahuddin** [comment]
I found solution by following [https://stackoverflow.com/questions/68268007/sublimeastyleformatter-not-formattting-java-c-in-sublime-text](url)
